#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  # Drag selected files out of Yazi with ripdrag
  # If no files are selected, %s expands to the hovered file.
  { on = [ "<C-n>" ], run = 'shell -- ripdrag %s -x 2>/dev/null &', desc = "Drag selected files with ripdrag" },

  # Your custom bookmarks
  { on = [ "g", "H" ], run = "cd /run/media/raviroy/T7", desc = "Go SSD home" },
  { on = [ "g", "C" ], run = "cd /run/media/raviroy/T7/01-MyStuffs/01-Academics/01-PhD/02-Coding", desc = "Goto Coding" },
  { on = [ "g", "P" ], run = "cd /run/media/raviroy/T7/01-MyStuffs/01-Academics/01-PhD/01-PDFs/", desc = "Goto PDFs" },

  # chmod plugin binding
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
]
