[mgr]
ratio = [1, 2, 4]

[plugin]
prepend_previewers = [
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]

prepend_fetchers = [
  { url = "*",  run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]

[opener]
edit = [
  { run = 'nvim %s', block = true, for = "unix" },
]
