#!/bin/sh
# /usr/bin/i3exit

# with openrc use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && logind=systemctl || logind=loginctl

case "$1" in
    lock)
        i3lock-fancy
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
         $logind suspend && i3lock-fancy
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | suspend | reboot | shutdown"
        exit 2
esac

exit 0

